# Generated by Django 3.2.5 on 2023-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('resumeid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('achievements', models.TextField()),
                ('experience', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
    ]
