# Generated by Django 3.2.5 on 2021-08-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeModel',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('AccountType', models.TextField()),
            ],
        ),
    ]
