# Generated by Django 3.2.5 on 2023-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
