# Generated by Django 3.2.5 on 2023-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
