# Generated by Django 3.2.5 on 2023-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('TempID', models.IntegerField(primary_key=True, serialize=False)),
                ('TempName', models.TextField()),
            ],
        ),
    ]
